"""recursive_data_transfer"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4ac790a42b41'
down_revision = '70ac6b86efb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_transfers', sa.Column('recursive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_transfers', 'recursive')
    # ### end Alembic commands ###
