"""add workflow profile"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'abfeeba56798'
down_revision = 'fffd1fac272e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workflows',
        sa.Column('profile', sa.JSON(), nullable=False, server_default='["mini_dbs"]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'profile')
    # ### end Alembic commands ###
