"""add credit update metatdata to users"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60712a56f2c2'
down_revision = 'bb952ec7e01c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('credit_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_users', sa.Column('credit_updated_by', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'credit_updated_by')
    op.drop_column('app_users', 'credit_updated_at')
    # ### end Alembic commands ###
