"""add credit to user"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb952ec7e01c'
down_revision = '797ec472e447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('credit', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'credit')
    # ### end Alembic commands ###
