"""service_usage"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f26ab5038ec'
down_revision = 'a6ee1af2c156'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('service_usage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'service_usage')
    # ### end Alembic commands ###
