"""queued_job_table"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0568b4aebd0'
down_revision = 'cb2033051aca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queued_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('workflow', sa.UUID(), nullable=False),
    sa.Column('launch_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow'], ['workflows.id'], name=op.f('fk_queued_jobs_workflow_workflows')),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_queued_jobs_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queued_jobs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queued_jobs')
    # ### end Alembic commands ###
