"""automatic grant sbp bundle users credits"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa8e5d81102'
down_revision = '328b94674d8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_users', sa.Column('sbp_bundle_credit_granted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_users', 'sbp_bundle_credit_granted_at')
    # ### end Alembic commands ###
