"""data_transfers"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ce352c6342'
down_revision = '4f26ab5038ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source_location', sa.Text(), nullable=False),
    sa.Column('destination_location', sa.Text(), nullable=False),
    sa.Column('transfer_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_data_transfers_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_transfers'))
    )
    op.add_column('run_inputs', sa.Column('data_transfer_id', sa.UUID(), nullable=True))
    op.add_column('run_outputs', sa.Column('data_transfer_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(op.f('uq_run_inputs_data_transfer_id'), 'run_inputs', ['data_transfer_id'])
    op.create_foreign_key(op.f('fk_run_inputs_data_transfer_id_data_transfers'), 'run_inputs', 'data_transfers', ['data_transfer_id'], ['id'])
    op.create_unique_constraint(op.f('uq_run_outputs_data_transfer_id'), 'run_outputs', ['data_transfer_id'])
    op.create_foreign_key(op.f('fk_run_outputs_data_transfer_id_data_transfers'), 'run_outputs', 'data_transfers', ['data_transfer_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_run_outputs_data_transfer_id_data_transfers'), 'run_outputs', type_='foreignkey')
    op.drop_constraint(op.f('uq_run_outputs_data_transfer_id'), 'run_outputs', type_='unique')
    op.drop_column('run_outputs', 'data_transfer_id')
    op.drop_constraint(op.f('fk_run_inputs_data_transfer_id_data_transfers'), 'run_inputs', type_='foreignkey')
    op.drop_constraint(op.f('uq_run_inputs_data_transfer_id'), 'run_inputs', type_='unique')
    op.drop_column('run_inputs', 'data_transfer_id')
    op.drop_table('data_transfers')
    # ### end Alembic commands ###
