"""add workflow_run credit_cost"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8ae645d1b3'
down_revision = 'abfeeba56798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('credit_cost', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'credit_cost')
    # ### end Alembic commands ###
