"""data_transfer_attempts"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffd1fac272e'
down_revision = 'cc2305398fd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'data_transfers',
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_transfers', 'attempts')
    # ### end Alembic commands ###
