"""add_config_path_to_workflows"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef9d934712f'
down_revision = '797ec472e447'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('config_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'config_path')
    # ### end Alembic commands ###
