"""null_seqera_id"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ab4858580d'
down_revision = '5d4995c0bdca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'seqera_run_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'seqera_run_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
