"""workflow_sync_status"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aae5c3e8e0'
down_revision = '4f26ab5038ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('seqera_final_status', sa.Text(), nullable=True))
    op.add_column('workflow_runs', sa.Column('sync_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'sync_completed_at')
    op.drop_column('workflow_runs', 'seqera_final_status')
    # ### end Alembic commands ###
