"""add_tool_and_require_core_fields_on_workflows"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a377a05de6e'
down_revision = '74ab4858580d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('tool', sa.Text(), nullable=True))
    op.alter_column('workflows', 'repo_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('workflows', 'default_revision',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('workflows', 'config_path',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'config_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('workflows', 'default_revision',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('workflows', 'repo_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('workflows', 'tool')
    # ### end Alembic commands ###
