"""add_unique_constraints_for_workflow_name_tool"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cff803a3b9'
down_revision = '7a377a05de6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_workflows_name'), 'workflows', ['name', 'tool'])
    op.create_index('uq_workflows_name_null_tool', 'workflows', ['name'], unique=True, postgresql_where=sa.text('tool IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_workflows_name_null_tool', table_name='workflows', postgresql_where=sa.text('tool IS NULL'))
    op.drop_constraint(op.f('uq_workflows_name'), 'workflows', type_='unique')
    # ### end Alembic commands ###
