"""data_transfers"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ce352c6342'
down_revision = '4f26ab5038ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('source_location', sa.Text(), nullable=False),
    sa.Column('destination_location', sa.Text(), nullable=False),
    sa.Column('transfer_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], name=op.f('fk_data_transfers_workflow_run_id_workflow_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_transfers'))
    )
    op.add_column('run_inputs', sa.Column('data_transfer_id', sa.UUID(), nullable=True))
    op.add_column('run_outputs', sa.Column('data_transfer_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###

    # Backfill a DataTransfer row for every pre-existing run_inputs/run_outputs
    # row (from before this table existed) so data_transfer_id can be made
    # NOT NULL below without dropping any existing input/output history.
    op.execute(sa.text("""
        CREATE TEMP TABLE _run_input_transfer_backfill AS
        SELECT
            ri.run_id,
            ri.s3_object_id,
            gen_random_uuid() AS data_transfer_id,
            s3."URI" AS source_location,
            wr.work_dir AS destination_location
        FROM run_inputs ri
        JOIN s3_objects s3 ON s3.object_key = ri.s3_object_id
        JOIN workflow_runs wr ON wr.id = ri.run_id
        WHERE ri.data_transfer_id IS NULL
    """))
    op.execute(sa.text("""
        INSERT INTO data_transfers
            (id, workflow_run_id, direction, provider, source_location, destination_location, status)
        SELECT data_transfer_id, run_id, 'input', 's3', source_location, destination_location, 'completed'
        FROM _run_input_transfer_backfill
    """))
    op.execute(sa.text("""
        UPDATE run_inputs ri
        SET data_transfer_id = b.data_transfer_id
        FROM _run_input_transfer_backfill b
        WHERE ri.run_id = b.run_id AND ri.s3_object_id = b.s3_object_id
    """))
    op.execute(sa.text("DROP TABLE _run_input_transfer_backfill"))

    op.execute(sa.text("""
        CREATE TEMP TABLE _run_output_transfer_backfill AS
        SELECT
            ro.run_id,
            ro.s3_object_id,
            gen_random_uuid() AS data_transfer_id,
            wr.work_dir AS source_location,
            s3."URI" AS destination_location
        FROM run_outputs ro
        JOIN s3_objects s3 ON s3.object_key = ro.s3_object_id
        JOIN workflow_runs wr ON wr.id = ro.run_id
        WHERE ro.data_transfer_id IS NULL
    """))
    op.execute(sa.text("""
        INSERT INTO data_transfers
            (id, workflow_run_id, direction, provider, source_location, destination_location, status)
        SELECT data_transfer_id, run_id, 'output', 's3', source_location, destination_location, 'completed'
        FROM _run_output_transfer_backfill
    """))
    op.execute(sa.text("""
        UPDATE run_outputs ro
        SET data_transfer_id = b.data_transfer_id
        FROM _run_output_transfer_backfill b
        WHERE ro.run_id = b.run_id AND ro.s3_object_id = b.s3_object_id
    """))
    op.execute(sa.text("DROP TABLE _run_output_transfer_backfill"))

    op.alter_column('run_inputs', 'data_transfer_id', nullable=False)
    op.alter_column('run_outputs', 'data_transfer_id', nullable=False)
    op.create_unique_constraint(op.f('uq_run_inputs_data_transfer_id'), 'run_inputs', ['data_transfer_id'])
    op.create_foreign_key(op.f('fk_run_inputs_data_transfer_id_data_transfers'), 'run_inputs', 'data_transfers', ['data_transfer_id'], ['id'])
    op.create_unique_constraint(op.f('uq_run_outputs_data_transfer_id'), 'run_outputs', ['data_transfer_id'])
    op.create_foreign_key(op.f('fk_run_outputs_data_transfer_id_data_transfers'), 'run_outputs', 'data_transfers', ['data_transfer_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_run_outputs_data_transfer_id_data_transfers'), 'run_outputs', type_='foreignkey')
    op.drop_constraint(op.f('uq_run_outputs_data_transfer_id'), 'run_outputs', type_='unique')
    op.drop_column('run_outputs', 'data_transfer_id')
    op.drop_constraint(op.f('fk_run_inputs_data_transfer_id_data_transfers'), 'run_inputs', type_='foreignkey')
    op.drop_constraint(op.f('uq_run_inputs_data_transfer_id'), 'run_inputs', type_='unique')
    op.drop_column('run_inputs', 'data_transfer_id')
    op.drop_table('data_transfers')
    # ### end Alembic commands ###
