"""add workflow ref_database"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'abfeeba56798'
down_revision = 'fffd1fac272e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workflows',
        sa.Column('ref_database', sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'ref_database')
    # ### end Alembic commands ###
