"""add submission_timestamp to workflow_runs"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0405f3482868'
down_revision = '91b54c7a79c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('submission_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'submission_timestamp')
    # ### end Alembic commands ###
